/* tslint:disable */
/* eslint-disable */
/**
 * GPT-Translator
 * The GPT translator API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from './apis/default-api';
export * from './apis/translator-api';

